version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/DONUT

hooks:
  BeforeInstall:
        - location: scripts/beforeInstall.bash
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  AfterInstall:
    - location: scripts/initialize.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root